### ISSUE TITLE
Delayed start field allows a start time in the past

### ISSUE THREAD

**Issue by Nickel33** [LowellInstruments/Domino#226]
0.6.3

If the delayed start is in the past, the mat.cfg file is allowed to be saved without any kind of a warning.   Domino should alert the user that the start time has passed.

**Comment by jeff101** [comment]
This little bug turned out to be a can of worms. I wanted the GUI to warn the user when setting start time in the past. However, if the user set the start time in the near future, it would be valid at set time, but would become invalid. After getting sick of edge cases and infinite loops, I threw in the towel and just made it a "post-save" check.

**Comment by Nickel33** [comment]
That works for me.  Verified fixed. 0.6.4.
